# Generated by Django 4.1.6 on 2023-02-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=250)),
                ('t_img', models.ImageField(upload_to='pics')),
                ('t_desc', models.TextField()),
            ],
        ),
    ]
